name: Nightly

on:
  repository_dispatch:
    types: nightly
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: circleci/android:api-29-node
      options: -u root
    env:
      KEYSTORE_PATH: ${{ github.workspace }}/insporation.jks

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.1.1
    - name: Setup keystore
      run: |
       echo "$KEYSTORE" | base64 -d > "$KEYSTORE_PATH"
      env:
        KEYSTORE: ${{ secrets.KEYSTORE }}
    - name: Build
      run: |
        flutter build apk --release --build-number=$GITHUB_RUN_NUMBER
        mkdir -p dist
        cp build/app/outputs/apk/release/app-release.apk dist/insporation-nightly-$(git describe --tags 2>/dev/null || echo $GITHUB_RUN_NUMBER).apk
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEYSTORE_KEY_ALIAS: key
    - uses: actions/upload-artifact@v1
      with:
        name: Application bundles
        path: dist
    - uses: marvinpinto/action-automatic-releases@v0.2.2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: nightly
    - uses: AButler/upload-release-assets@v2.0
      with:
        files: 'dist/*'
        release-tag: nightly
        repo-token: ${{ secrets.GITHUB_TOKEN }}