name: Nightly

on:
  repository_dispatch:
    types: nightly

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: circleci/android:api-29-node
      options: -u root
    env:
      KEYSTORE_PATH: ${{ github.workspace }}/insporation.jks
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.1.1
    - name: Setup keystore
      run: |
       echo "$KEYSTORE" | base64 -d > "$KEYSTORE_PATH"
      env:
        KEYSTORE: ${{ secrets.KEYSTORE }}
    - name: Build
      run: |
        flutter build apk --release --build-number=$GITHUB_RUN_NUMBER
        mkdir -p dist
        cp build/app/outputs/apk/release/app-release.apk dist/insporation-nightly-$(git describe --tags 2>/dev/null || echo $GITHUB_RUN_NUMBER).apk
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEYSTORE_KEY_ALIAS: key
    - uses: actions/upload-artifact@v1
      with:
        name: Application bundles
        path: dist
  publish:
    needs: build
    runs-on: ubuntu-latest
    container:
      imafge: cgeo/fdroid-base
      options: -u root
    env:
      KEYSTORE_PATH: ${{ github.workspace }}/insporation.jks
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    steps:
    - name: Update git
      run: |
        add-apt-repository ppa:git-core/ppa
        apt update
        apt install git
    - uses: actions/download-artifact@v1
      with:
        name: Application bundles
        path: dist
    - uses: marvinpinto/action-automatic-releases@v0.2.2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: nightly
    - uses: AButler/upload-release-assets@v2.0
      with:
        files: 'dist/*'
        release-tag: nightly
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout F-Droid repository
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: pages
    - name: Setup keystore
      run: |
       echo "$KEYSTORE" | base64 -d > "$KEYSTORE_PATH"
      env:
        KEYSTORE: ${{ secrets.KEYSTORE }}
    - name: Update F-Droid repository
      run: |
        cp dist/*.apk pages/fdroid/repo
        cd pages/fdroid
        fdroid update
        git config --local user.email "me+nightly-ci@jhass.eu"
        git config --local user.name  "Github Actions Nightly Job"
        git add .
        git commit -m "Update fdroid repository for nightly build $GITHUB_RUN_NUMBER"
        git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git" gh-pages
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEYSTORE_KEY_ALIAS: key